quarkus.http.port=${PORT:8080}

#Configuraciones DB
quarkus.datasource.db-kind = mssql
quarkus.datasource.username = ${DB_USR}
quarkus.datasource.password = ${PWD}
quarkus.datasource.jdbc.url = ${DB_URL}
quarkus.datasource.db-version=12.0.0

#Configuraciones Keycloak
quarkus.oidc.auth-server-url=${KEYCLOAK_URL}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT}
quarkus.oidc.credentials.secret=${KEYCLOAK_SECRET}
quarkus.oidc.token.allow-jwt-introspection=true
quarkus.oidc.token.require-jwt-introspection-only=true
quarkus.oidc.application-type=service

quarkus.http.cors.enabled=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Origin,Accept,Content-Type,X-Requested-With,Authorization

quarkus.http.cors.exposed-headers=
quarkus.http.cors.max-age=3600
quarkus.http.cors.supports-credentials=false

quarkus.package.type=uber-jar

quarkus.oidc.devservices.enabled=false
quarkus.keycloak.devservices.enabled=false
quarkus.datasource.devservices.enabled=false